plexe-ai/plexe

.github/workflows/integration.yml
This pull request introduces a new GitHub Actions workflow for integration testing. The workflow is triggered by various events and runs on the latest Ubuntu environment. It sets up Python, installs dependencies using Poetry, and runs tests using pytest.
Key changes:
* Added a new workflow named `Integration` in `.github/workflows/integration.yml` that triggers on `workflow_dispatch`, `push`, and `pull_request` events.
* Configured the workflow to run on `ubuntu-latest` and included steps to checkout the code, set up Python 3.12, install dependencies with Poetry, and run tests using pytest.
=> Add integration.yml for ci steps

pyproject.toml, smolmodels/internal/models/search/random_policy.py
This pull request fixes a bug whereby the node expansion selection logic fails if no "good" nodes exist yet in the graph. Now the function prefers good nodes, but can also return buggy nodes if not enough good nodes are available.
* [`smolmodels/internal/models/search/random_policy.py`](diffhunk://#diff-d66f8349c632f192a8a3f3074f24061efedccab1b49493aa9ae0a26eb31086feL70-R82): The method now prefers to expand visited good nodes first, and if necessary, expands visited buggy nodes. It also ensures that if no nodes have been visited, the first node is returned. This change enhances the robustness and accuracy of node selection.
=> fix: random search policy expansion bug

.github/workflows/publish.yml, .github/workflows/semantic-release.yml
Fix `semantic-release` workflow by:
- Installing poetry directly rather than using container
- Using pip to install semantic-release instead of the action
- Running semantic-release in dry-run mode when testing
=> fix: semantic release GA

pyproject.toml
This PR bumps the package version, because we forgot to do this in the previous PR. ⛔
=> Chore: bump version to 0.1.2

README.md, poetry.lock, pyproject.toml, smolmodels/config.py, smolmodels/internal/common/datasets/adapter.py, smolmodels/internal/models/execution/process_executor.py, smolmodels/models.py, tests/unit/internal/models/execution/test_process_executor.py, tests/unit/test_data_generation.py
This PR aims to improve the consistency and extensibility of the library's handling of datasets. Previously the input dataset could be either a `str` or a `pandas.DataFrame`, but if it was a string, it was implicitly assumed that this had to be referring to a CSV file. This was a confusing and irritating user experience.
Now, the library no longer allows filling the `dataset` parameter with a path, which means we don't have to support loading all sorts of different file types on our side. Instead, the user can pass a dataset object directly, allowing them to handle the data loading using whatever tools suit their workflow. Currently, only `pandas.DataFrame` and `numpy.ndarray` are supported, but we'll add support for other dataset types in the future.
This PR begins to address the problem …
=> feature: support common datasets

poetry.lock, pyproject.toml, smolmodels/config.py
This PR adds `torch` (the cpu-only version) to the project dependencies and the list of packages the model generation is allowed to use. This means the model generation can now generate deep learning solutions using PyTorch.
=> feature: add torch (cpu) to supported packages

pyproject.toml, smolmodels/config.py, smolmodels/internal/data_generation/__init__.py
This PR fixes an issue whereby the library actually makes changes to the `logging` library's root logger. What this means is that it won't play nice with a wider project that is using `smolmodels`.
=> fix: configure logging without modifying root logger

README.md
This PR makes a minor adjustment to the "early release" warning to make it more concise and helpful.
=> fix: change early release banner to be more helpful

README.md
Remove PyPI badge from readme as the number is not reliable.
=> chore: remove PyPI downloads badge from readme

poetry.lock, pyproject.toml, smolmodels/config.py, tests/integration/test_model_integration.py
- Fixed `AttributeError: 'OutStream' object has no attribute 'reconfigure'` in the logging configuration.
- Updated torch dependency to support multiple Python versions to ensure compatibility across environments.
=> Fix: handle logging reconfigure error for Jupyter & update torch dependency

README.md
Previous Discord link had expired as it was only valid for 7 days.
=> fix: update previously expired discord link

README.md, pyproject.toml, smolmodels/internal/common/provider.py
PR to address #61.
While there was a retry mechanism in place using the tenacity library, it was only being applied to the API call itself in the `call_with_backoff()` function. However, when a rate limit error occurs, it's being caught in the outer try-except block and immediately re-raised without any retry logic. This PR fixes this by:
- Moving the retry decorator to wrap the entire API call process
- Adding specific retry conditions for rate limit errors
=> fix: retry implementation for providers

poetry.lock, pyproject.toml
Whenever `smolmodels` is used in a different project, it always throws an error due to missing `black` as it is used in `response.py`.
=> fix: import for dependencies

.github/workflows/integration.yml, README.md, poetry.lock, pyproject.toml, setup.py, smolmodels/config.py, smolmodels/internal/common/utils/dependency_utils.py, tox.ini
This PR adds the ability to install a "lightweight" variant of the library without heavy deep learning dependencies. In most ML tasks the quality of your model is determined by the quality and size of your data, rather than the algorithm being used, so it makes sense to give users the option to use a "no deep learning" backend if they prefer a lightweight installation.
The variants are detailed in the readme, but in a nutshell:
1. `smolmodels`: default installation, required packages only
2. `smolmodels[lightweight]`: same as default
3. `smolmodels[all]`: includes deep learning
The LLM prompts for code generation take into account whether DL libraries are available. The tox setup for tests and GH actions workflow have been updated as well.
=> feat: add option for lightweight installation

pyproject.toml, smolmodels/internal/models/generation/inference.py
This PR fixes a bug that prevents `smolmodels` from being used for inference in a different environment than the one in which it was trained. The bug is caused by an absolute file path being inserted into the "predictor" code. The absolute path is valid in the env in which the model was trained, but most likely does not exist in a different env to which you want to deploy the model.
=> fix: generated predictor code uses abs paths

pyproject.toml, smolmodels/config.py, smolmodels/fileio.py, smolmodels/internal/models/generators.py
This PR addresses a few minor model quality issues, which I spotted when I encountered a case of a "heart attack prediction" model which kept returning a label `1` no matter how I changed the inputs. None of these changes guarantee such a model would not be built again.
1. The "come up with a plan" prompt does not include the metric to optimise for. I suspect this is the reason why we often see training runs that do not produce the right metric.
2. Some minor logging improvements.
=> hotfix: planning prompt does not include metric to optimise

pyproject.toml, smolmodels/config.py, smolmodels/internal/models/execution/process_executor.py, smolmodels/internal/models/generators.py, smolmodels/models.py
This PR fixes a bug whereby model training runs always have a fixed timeout of 300 seconds. This bug likely largely explains the high % of model build failures whenever the ML task is any more complex than a toy problem. This PR also adds explicit handling for timeout errors when running a model build, so that timeouts at the individual run level are properly flagged in terminal output.
=> feat: add explicit per-run timeout + logging

README.md
This PR makes some minor changes to the readme to remove parts that are out of date and link to the LiteLLM docs for model provider usage.
=> fix: remove cli usage from readme

plexe/internal/agents.py, plexe/internal/models/tools/execution.py, plexe/models.py, tests/integration/test_ray_integration.py, tests/unit/internal/models/execution/test_factory.py
Wrap the `execute_code` tool in a closure so the agent doesn't have to pass the "distributed" flag to the tool.
=> refactor: ray executor without tool change

plexe/internal/models/execution/process_executor.py, plexe/internal/models/tools/execution.py, pyproject.toml
This PR ensures `ProcessExecutor` cleans up datasets and other files it writes for model training. No more disk space hogging due to large datasets being copied over and over again!
The PR also slightly simplifies and cleans up the error handling logic in `ProcessExecutor`.
=> fix: make process executor clean up after itself

plexe/internal/common/utils/response.py, plexe/internal/models/execution/executor.py, plexe/internal/models/execution/process_executor.py, plexe/internal/models/tools/execution.py, pyproject.toml, tests/unit/internal/models/execution/test_process_executor.py
This PR makes a number of small improvements to the error handling that wraps ML training code execution:
1. Consolidated logic for detecting invalid or missing performance metric
2. Raise error when performance is missing instead of logging it; it's the LLM that needs to read the error, not the user
3. A few miscellaneous little fixes here and there
=> fix: improve process executor error handling

README.md
Tiny PR to add a BibTex citation to the README, so that anyone using Plexe in research work can provide correct attribution.
=> docs: add bibtext citation to readme

README.md
This PR addresses issue #77 by adding an explicit mention of support for open LLM providers (Ollama, HuggingFace, etc) to the readme.
=> docs: add ollama to readme

docs/architecture/multi-agent-system.md, plexe/__init__.py, plexe/agents/conversational.py, plexe/callbacks.py, plexe/core/storage.py, plexe/internal/models/callbacks/mlflow.py, plexe/main.py, plexe/model_builder.py, plexe/models.py, plexe/templates/prompts/agent/conversational_prompt_templates.yaml, plexe/tools/conversation.py
This PR adds a simple "chat agent" to the library to enable a user to start the model building via a chat. The user should run
```python
python plexe/main.py
```
to start the chat. This will open a simple GradioUI that is suitable for testing. The chat agent itself is available in `plexe/agents/conversational.py` and can be hooked up into other front-ends etc.
This PR also deprecates (but does not remove) the `Model.build()` function. Until now, the `Model` class has been mixing two responsibilities:
1. Representing a model that can be used for inference, serialised, deserialised, etc
2. Wrapped the entire agent system that builds the models
The model building logic has been moved to a new class, `ModelBuilder`, which exposes a function `ModelBuilder.build() -> Model`. The `Model` class …
=> feature: conversational interface

README.md, poetry.lock, pyproject.toml
This PR separates the chat UI dependencies from the rest of the project. The dependencies `uvicorn`, `websockets` and `fastapi` were causing conflicts when installing `plexe` in a backend that already defines those dependencies itself.
=> chore: update dependencies/extras grouping

examples/house_prices.py
The current example is outdated and still uses a model that the code indicates is deprecated. I have updated it to the latest version using the model builder.
=> feat: Update example
